#!/usr/bin/php
<?php

/*
    This file is part of TRC Ninja.
    https://github.com/terracoin/trcninja-ctl

    TRC Ninja is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    TRC Ninja is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TRC Ninja.  If not, see <http://www.gnu.org/licenses/>.

 */

require_once("tmn.functions.inc.php");

function tempdir($prefix='php') {
    $tempfile=tempnam(sys_get_temp_dir(),$prefix);
    if (file_exists($tempfile)) { unlink($tempfile); }
    mkdir($tempfile);
    if (is_dir($tempfile)) { return $tempfile; }
}

function delTree($dir) {
  $files = array_diff(scandir($dir), array('.','..'));
  foreach ($files as $file) {
    (is_dir("$dir/$file")) ? delTree("$dir/$file") : unlink("$dir/$file");
  }
  return rmdir($dir);
}

xecho("terracoind auto updater (testnet) v1.0\n");
xecho("Retrieving current latest binary date and size: ");
$test = get_headers("https://terracoin.io/bin/terracoin-core-current/terracoin-0.12.2-x86_64-linux-gnu.tar.gz", 1);
echo $test["Last-Modified"]."\n";

$datanew = sha1(serialize(array("Last-Modified" => $test["Last-Modified"],
                                "Content-Length" => $test["Content-Length"])));
xecho("Retrieving current binary date and size: ");
$dataold = file_get_contents(TMN_DIR."terracoindupdate.php.lasthash");
echo "OK\n";

if ($datanew != $dataold) {
  file_put_contents(TMN_DIR."/terracoindupdate.php.lasthash",$datanew);
  xecho("Stopping testnet nodes... ");
  passthru(TMN_DIR."/tmnctl stop testnet");
  passthru(TMN_DIR."/tmnctl stop testnet p2pool");
  xecho("Reseting data (not the blockchain/wallet)... ");
  passthru(TMN_DIR."/tmnreset test ttmn01",$output);
  passthru(TMN_DIR."/tmnreset test ttmn02");
  passthru(TMN_DIR."/tmnreset test ttmn03");
  passthru(TMN_DIR."/tmnreset test ttmn04");
  passthru(TMN_DIR."/tmnreset test tp2pool");
  xecho("Getting new binary: ");
  $tmpdir = tempdir("terracoindupdater");
  $curdir = getcwd();
  chdir($tmpdir);
  passthru("wget -q https://terracoin.io/bin/terracoin-core-current/terracoin-0.12.2-x86_64-linux-gnu.tar.gz");
  echo "OK... Untar: ";
  passthru("tar xvf terracoin-0.12.2-x86_64-linux-gnu.tar.gz");
  echo "OK... Version: ";
  $fnam = $tmpdir."/terracoin-0.12.2/bin/terracoind";
  $versionraw = tmn_terracoindversion($fnam);
  echo $versionraw."... Moving: ";
  $fnamnew = "/opt/terracoind/0.12/terracoind-$versionraw";
  rename($fnam,$fnamnew);
  echo "OK... Submitting to DB: ";
  passthru("tmnctl version $fnamnew $versionraw 1 1");
  echo "OK\n";
  chdir($curdir);
  delTree($tmpdir);
  xecho("Starting testnet nodes with re-index... ");
  unlink("/var/www/trcninja/cache/trcninja_cmd_getnodes_1");
  passthru(TMN_DIR."/tmnctl start testnet masternode reindex");
  passthru(TMN_DIR."/tmnctl start testnet p2pool reindex");
  echo "OK\n";
}

?>
