#!/bin/zsh
#
#   This file is part of TRC Ninja.
#   https://github.com/terracoin/trcninja-ctl
#
#   TRC Ninja is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   TRC Ninja is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with TRC Ninja.  If not, see <http://www.gnu.org/licenses/>.
#

# Disable logging by default
updatelog=/dev/null
statuslog=/dev/null
votesrrdlog=/dev/null
balancelog=/dev/null
portchecklog=/dev/null
autoupdatelog=/dev/null

# If parameter 1 is log then enable logging
if [[ "$1" == "log" ]]; then
  updatelog=/var/log/tmn/update.log
  statuslog=/var/log/tmn/status.log
  votesrrdlog=/var/log/tmn/votesrrd.log
  balancelog=/var/log/tmn/balance.log
  portchecklog=/var/log/tmn/portcheck.log
  autoupdatelog=/var/log/tmn/autoupdate.log
fi

# Sequentially run scripts
#/opt/tmnctl/terracoindupdate >> $updatelog
/opt/tmnctl/tmnctl status >> $statuslog
#/opt/tmnctl/tmnvotesrrd >> $votesrrdlog
/usr/bin/php /opt/tmnctl/tmndbgen masternodeactive >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main nodesstatus >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main blocksconsensus >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main votelimit >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main masternodeslistfull >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main governanceproposals >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main governancetriggers >> $statuslog
/usr/bin/php /var/www/trcninja/api/cron.php main blockssuperblocks >> $statuslog

# Concurrently run scripts
/usr/bin/nice -n 18 /opt/tmnctl/tmnbalance >> $balancelog &
/usr/bin/nice -n 19 /opt/tmnctl/tmnportcheck db >> $portchecklog &
/usr/bin/nice -n 15 /opt/tmnctl/tmnautoupdate >> $autoupdatelog &
